apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbackend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lk8s-backend
  template:
    metadata:
      labels:
        app: lk8s-backend
    spec:
      containers:
      - name: k8s-backendcontainer
        image: gcr.io/somnath007-402206/k8s-backend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: lk8s-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
