apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbackend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lk8s-backend
  template:
    metadata:
      labels:
        app: lk8s-backend
    spec:
      containers:
      - name: k8s-backendcontainer
        image: gcr.io/somnath007-402206/k8s-backend:latest
        ports:
        - containerPort: 8080
